# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willy', '0002_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='scheduled_date',
        ),
    ]
