# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('willy', '0003_remove_command_scheduled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_events', to='willy.Device')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_events', to='willy.Device')),
            ],
        ),
    ]
