# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('willy', '0004_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['scheduled_time']},
        ),
        migrations.AlterField(
            model_name='event',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_events', to='willy.Command'),
        ),
    ]
