# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willy', '0005_auto_20170519_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='code',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
