# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willy', '0006_command_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='everyday',
            field=models.BooleanField(default=False),
        ),
    ]
