# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willy', '0007_event_everyday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='code',
            field=models.CharField(default=b'', max_length=2000),
        ),
    ]
